name: Publish NPM packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.6
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build affected projects
        run: pnpm -r run ci

      - name: Check affected projects
        run: pnpm -r publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
